/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package syscovid;

import java.awt.HeadlessException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.*;


/**
 *
 * @author Acer
 */
public class RegisterFormStudent extends javax.swing.JFrame {
     //declaration
    ArrayList<Student> studentList;
   ArrayList<Postgraduate> postList;
    ArrayList<Undergraduate> underList;
    
       
    

    /**
     * Creates new form RegisterForm
     */
    public RegisterFormStudent() {
        initComponents();
        //center the location
        this.setLocationRelativeTo(null);
        studentList = new ArrayList<Student>();
        postList = new ArrayList<Postgraduate>();
        underList = new ArrayList<Undergraduate>();
        groupButton();
        groupButton1();
        groupButton2();
        groupButton3();
    }
    private void groupButton( ) {

    ButtonGroup bg1 = new ButtonGroup( );

        bg1.add(R_post);
        bg1.add(R_Under);

    }
    private void groupButton1( ) {

    ButtonGroup bg2 = new ButtonGroup( );

        bg2.add(fulltime);
        bg2.add(part_time);

    }
    private void groupButton2( ) {

    ButtonGroup bg1 = new ButtonGroup( );

        bg1.add(B_home);
        bg1.add(B_UTM);
        bg1.add(B_other);

    }
    private void groupButton3( ) {

    ButtonGroup bg2 = new ButtonGroup( );

        bg2.add(utmjb);
        bg2.add(utmkl);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_metric = new javax.swing.JTextField();
        first_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        combo_program = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        B_home = new javax.swing.JRadioButton();
        B_UTM = new javax.swing.JRadioButton();
        B_other = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        B_signUp = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        R_post = new javax.swing.JRadioButton();
        R_Under = new javax.swing.JRadioButton();
        combo_state = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        fulltime = new javax.swing.JRadioButton();
        part_time = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        utmjb = new javax.swing.JRadioButton();
        utmkl = new javax.swing.JRadioButton();
        pass1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        text_program = new javax.swing.JComboBox<>();
        text_year = new javax.swing.JComboBox<>();
        last_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Metric No. *");

        first_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_nameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone No. *");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("College");

        combo_program.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "KTDI", "K910", "KDOJ", "KTHO", "KTC", "KDSE", "KRP", "KP", "KTR", "KTF", "Other" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Program * ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Year");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Current Location");

        B_home.setBackground(new java.awt.Color(0, 51, 102));
        B_home.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B_home.setForeground(new java.awt.Color(255, 255, 255));
        B_home.setText("Home");
        B_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        B_UTM.setBackground(new java.awt.Color(0, 51, 102));
        B_UTM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B_UTM.setForeground(new java.awt.Color(255, 255, 255));
        B_UTM.setText("UTMJB/KL");
        B_UTM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        B_other.setBackground(new java.awt.Color(0, 51, 102));
        B_other.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        B_other.setForeground(new java.awt.Color(255, 255, 255));
        B_other.setText("Other");
        B_other.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("State");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Create a password *");

        B_signUp.setBackground(new java.awt.Color(0, 153, 51));
        B_signUp.setText("Submit");
        B_signUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_signUpActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Cancel");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Category");

        R_post.setBackground(new java.awt.Color(0, 51, 102));
        R_post.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        R_post.setForeground(new java.awt.Color(255, 255, 255));
        R_post.setText("Postgraduate");
        R_post.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        R_Under.setBackground(new java.awt.Color(0, 51, 102));
        R_Under.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        R_Under.setForeground(new java.awt.Color(255, 255, 255));
        R_Under.setText("Undergraduate");
        R_Under.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        combo_state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Wilayah_Persekutuan", "Selangor", "Melaka", "Johor_Bahru", "N.Sembilan", "Kedah", "Perlis", "Perak", "Pulau_Pinang", "Pahang", "Terengganu", "Kelantan", "Sabah", "Sarawak" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Status (Only for posgraduate student)");

        fulltime.setBackground(new java.awt.Color(0, 51, 102));
        fulltime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fulltime.setForeground(new java.awt.Color(255, 255, 255));
        fulltime.setText("Full Time");
        fulltime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        part_time.setBackground(new java.awt.Color(0, 51, 102));
        part_time.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        part_time.setForeground(new java.awt.Color(255, 255, 255));
        part_time.setText("Part Time");
        part_time.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Study Place (Only for undergraduate student)");

        utmjb.setBackground(new java.awt.Color(0, 51, 102));
        utmjb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        utmjb.setForeground(new java.awt.Color(255, 255, 255));
        utmjb.setText("UTMJB");
        utmjb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        utmkl.setBackground(new java.awt.Color(0, 51, 102));
        utmkl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        utmkl.setForeground(new java.awt.Color(255, 255, 255));
        utmkl.setText("UTMKL");
        utmkl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("STUDENT REGISTRATION");

        text_program.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "SCSR/SECR", "SCSV/SECV", "SCSB/SECB", "SCSJ/SECJ", "SCSP/SECP" }));

        text_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "1", "2", "3", "4", "Other" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("eg: Ahmad Johan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(text_metric)
                        .addComponent(text_phone)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(last_name, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))))
                    .addComponent(jLabel11)
                    .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(fulltime)
                                .addGap(27, 27, 27)
                                .addComponent(part_time))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(R_post)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(R_Under)))
                            .addComponent(B_signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10)
                                .addComponent(jLabel5)
                                .addComponent(combo_state, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combo_program, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(B_home)
                                    .addGap(18, 18, 18)
                                    .addComponent(B_UTM)
                                    .addGap(18, 18, 18)
                                    .addComponent(B_other)))
                            .addGap(40, 40, 40))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(utmjb)
                                    .addGap(40, 40, 40)
                                    .addComponent(utmkl))
                                .addComponent(jLabel15))
                            .addContainerGap()))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_year, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(text_program, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_program, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_program, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_home)
                            .addComponent(B_UTM)
                            .addComponent(B_other)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_metric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R_Under)
                    .addComponent(R_post))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fulltime)
                    .addComponent(part_time)
                    .addComponent(utmjb)
                    .addComponent(utmkl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Thank You");
        this.hide();
        new LoginStaff().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void B_signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_signUpActionPerformed
        // TODO add your handling code here
        String firstName = first_name.getText().toUpperCase().toString();
        String lastName = last_name.getText().toUpperCase().toString();
        String sMetric = text_metric.getText().toUpperCase();
        //String sBlock = text_block.getText().toUpperCase();
        //String sCity = (String)text_city.getSelectedItem();

        String sYear = (String) text_year.getSelectedItem();
        String sPhone = text_phone.getText();
        String sProgram  = (String)text_program.getSelectedItem();
        String passField = pass1.getText();
        String sPlace="";

        //private JPasswordField passField;

        //college
        String kolej1 = (String)combo_program.getSelectedItem();
        String state = (String)combo_state.getSelectedItem();

        //current location
        String _currentLocation = "";
        if(B_home.isSelected())
        {
            _currentLocation = B_home.getText();
        }
        else if(B_UTM.isSelected())
        {
            _currentLocation = B_UTM.getText();
        }
        else if(B_other.isSelected())
        {
            _currentLocation = B_other.getText();
        }

        ////category
        String scategory="";
        String statPost ="";
        if(R_post.isSelected())
        {
            if(fulltime.isSelected())
            {
                statPost = fulltime.getText();
            }
            else if(part_time.isSelected())
            {
                statPost = part_time.getText();
            }
            scategory = R_post.getText();
        }
        else if(R_Under.isSelected())
        {
            if(utmjb.isSelected())
            {
                sPlace = utmjb.getText();
            }
            else if(utmkl.isSelected())
            {
                sPlace = utmkl.getText();
            }
            scategory = R_Under.getText();
        }

        try
        {
            if(R_post.isSelected())
            {
                Postgraduate sPost = new Postgraduate(firstName,lastName,sMetric,sPhone,passField,scategory,sProgram,state,kolej1,_currentLocation, sYear,statPost);
                postList.add(new Postgraduate(firstName,lastName,sMetric,sPhone,passField,scategory,sProgram,state,kolej1,_currentLocation, sYear,statPost));
                studentList.add(sPost);
                FileWriter writer = new FileWriter("Postgraduate.txt",true);
                //PrintWriter pWrite = new PrintWriter(writer);
                writer.write(""+sMetric+" "+passField+" "+firstName+" "+lastName+" "+sPhone+" "+scategory+" "+sProgram+" "+state+" "+kolej1+" "+_currentLocation+" "+sYear+" "+statPost);
                writer.write("\n");
//                for(int i=0; i<studentList.size();i++)
//                {
//                    pWrite.print(studentList.get(i).display());
//                }
                writer.close();
                JOptionPane.showMessageDialog(null, "Registration Success");
                new LoginStudent().setVisible(true);
                this.setVisible(false);
            }
            if(R_Under.isSelected())
            {
                Undergraduate sUnder = new Undergraduate(firstName,lastName,sMetric,sPhone,passField,scategory,sProgram,state,kolej1,_currentLocation, sYear,sPlace);
                underList.add(new Undergraduate(firstName,lastName,sMetric,sPhone,passField,scategory,sProgram,state,kolej1,_currentLocation, sYear,sPlace));
                studentList.add(sUnder);
                FileWriter writer = new FileWriter("Undergraduate.txt",true);
                //PrintWriter pWrite = new PrintWriter(writer);

                //pWrite.printf("\n%-20s%-10s%-10s%-10s%-10s%-10s%-10s%-10s%-20s%-1s0%-10s%-10s%-10s",sName,sMetric,sPhone,passField,scategory,sProgram,sYear,sBlock,kolej1,_currentLocation,sCity,state,sPlace);
                //writer.write(sMetric);
                //writer.write("\n");
                writer.write(""+sMetric+" "+passField+" "+firstName+" "+lastName+" "+sPhone+" "+scategory+" "+sProgram+" "+state+" "+kolej1+" "+_currentLocation+" "+sYear+" "+sPlace);
                writer.write("\n");
                // writer.write(System.getProperty("line.separator"));
                writer.close();
                JOptionPane.showMessageDialog(null, "Registration Success");
                new LoginStudent().setVisible(true);
                this.setVisible(false);
            }

        } catch(HeadlessException | IOException e){

            JOptionPane.showMessageDialog(null, "Registration Failed");
        }

    }//GEN-LAST:event_B_signUpActionPerformed

    private void first_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_nameActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Thank You");
        this.hide();
        new MainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_first_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFormStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFormStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton B_UTM;
    private javax.swing.JRadioButton B_home;
    private javax.swing.JRadioButton B_other;
    private javax.swing.JButton B_signUp;
    private javax.swing.JRadioButton R_Under;
    private javax.swing.JRadioButton R_post;
    private javax.swing.JComboBox<String> combo_program;
    private javax.swing.JComboBox<String> combo_state;
    private javax.swing.JTextField first_name;
    private javax.swing.JRadioButton fulltime;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField last_name;
    private javax.swing.JRadioButton part_time;
    private javax.swing.JTextField pass1;
    private javax.swing.JTextField text_metric;
    private javax.swing.JTextField text_phone;
    private javax.swing.JComboBox<String> text_program;
    private javax.swing.JComboBox<String> text_year;
    private javax.swing.JRadioButton utmjb;
    private javax.swing.JRadioButton utmkl;
    // End of variables declaration//GEN-END:variables

    private boolean isPasswordCorrect(char[] input) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
