/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package syscovid;

import java.io.FileReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author amie
 */
public class UpdateLocationStudent extends javax.swing.JFrame {

    /**
     * Creates new form UpdateLocationStudent
     */
    public UpdateLocationStudent() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        metricUpdate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        locationUpdate = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        stateUpdate = new javax.swing.JComboBox<>();
        submitUpdate = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Location");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Metric No.");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Current Location");

        locationUpdate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        locationUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Home", "UTMJB/KL", "Other" }));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("State");

        stateUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Wilayah_Persekutuan", "Selangor", "Melaka", "Johor_Bahru", "N.Sembilan", "Kedah", "Perlis", "Perak", "Pulau_Pinang", "Pahang", "Terengganu", "Kelantan", "Sabah", "Sarawak" }));

        submitUpdate.setBackground(new java.awt.Color(0, 204, 0));
        submitUpdate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        submitUpdate.setText("Submit");
        submitUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitUpdateActionPerformed(evt);
            }
        });

        logOutBtn.setBackground(new java.awt.Color(255, 0, 0));
        logOutBtn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(metricUpdate)
                            .addComponent(jLabel3)
                            .addComponent(locationUpdate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stateUpdate, 0, 257, Short.MAX_VALUE)
                            .addComponent(submitUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(metricUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stateUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitUpdateActionPerformed
        // TODO add your handling code here:
        String searchID = metricUpdate.getText().toUpperCase();
        String locUpdate = (String) locationUpdate.getSelectedItem();
        String negUpdate = (String) stateUpdate.getSelectedItem();

        ArrayList<String>tempArray = new ArrayList<>();
        ArrayList<String>postArray = new ArrayList<>();
        try
        {
            try
            {
                FileReader fr = new FileReader("Undergraduate.txt");
                Scanner reader = new Scanner(fr);
                String line;
                String[] lineArray;
                while((line = reader.nextLine())!=null){
                    lineArray = line.split(" ",0);
                    if(lineArray[0].equals(searchID)){
                        tempArray.add(
                            lineArray[0] + " " +
                            lineArray[1] + " " +
                            lineArray[2] + " " +
                            lineArray[3] + " " +
                            lineArray[4] + " " +
                            lineArray[5] + " " +
                            lineArray[6] + " " +
                            negUpdate + " " +
                            lineArray[8] + " " +
                            locUpdate + "  " +
                            lineArray[10] + " " +
                            lineArray[11]);
                        
                        JOptionPane.showMessageDialog(null, "Success");
                    }else {
                        tempArray.add(line);
                    }
                }

                fr.close();

            } catch (Exception e){

            }
            try{
                try(PrintWriter pr = new PrintWriter("Undergraduate.txt")){

                    for(String str : tempArray )
                    {
                        pr.println(str);
                    }
                    pr.close();
                }catch(Exception e){

                }
            }catch(Exception e){

            }

        } catch(Exception e){

        }

        //        //POSTGRADUATE
        try
        {
            try
            {
                FileReader pp = new FileReader("Postgraduate.txt");
                Scanner readerPost = new Scanner(pp);
                String pg;
                String[] linePg;
                while((pg = readerPost.nextLine())!=null){
                    linePg = pg.split(" ",0);
                    if(linePg[0].equals(searchID)){
                        postArray.add(
                            linePg[0] + " " +
                            linePg[1] + " " +
                            linePg[2] + " " +
                            linePg[3] + " " +
                            linePg[4] + " " +
                            linePg[5] + " " +
                            linePg[6] + " " +
                            negUpdate + " " +
                            linePg[8] + " " +
                            locUpdate + " " +
                            linePg[10] + " " +
                            linePg[11]);
                        
                        JOptionPane.showMessageDialog(null, "Success");
                        
                    }else {
                        postArray.add(pg);
                    }
                }

                pp.close();

            } catch (Exception e){

            }
            try{
                try(PrintWriter pu = new PrintWriter("Postgraduate.txt")){

                    for(String star : postArray )
                    {
                        pu.println(star);
                    }
                    pu.close();
                }catch(Exception e){

                }
            }catch(Exception e){

            }

        } catch(Exception e){

        }
    }//GEN-LAST:event_submitUpdateActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        this.hide();
        new LoginStudent().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateLocationStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateLocationStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateLocationStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateLocationStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateLocationStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> locationUpdate;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JTextField metricUpdate;
    private javax.swing.JComboBox<String> stateUpdate;
    private javax.swing.JButton submitUpdate;
    // End of variables declaration//GEN-END:variables
}
