/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package syscovid;

import java.io.FileReader;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author amie
 */
public class ViewStudentLocation extends javax.swing.JFrame {

        int TState = 0;
        int wilayah = 0;
        int selangor = 0; int melaka = 0; int JB = 0;int ns = 0; int kedah = 0;
        int perlis = 0; 
        int perak = 0; 
        int pp = 0; 
        int pahang = 0; 
        int kelantan = 0; 
        int sabah = 0; 
        int sar = 0;
        int home =0;
    /**
     * Creates new form ViewStudentLocation
     */
    public ViewStudentLocation() {
       
         initComponents();
         //groupButton1();
         this.setLocationRelativeTo(null);
        
        area1.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        viewState = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();
        viewHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        viewUTM = new javax.swing.JButton();
        viewOther = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        viewState.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        viewState.setText("State");
        viewState.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStateActionPerformed(evt);
            }
        });

        area1.setColumns(20);
        area1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        area1.setRows(5);
        jScrollPane2.setViewportView(area1);

        viewHome.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        viewHome.setText("Home");
        viewHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View category by");

        viewUTM.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        viewUTM.setText("UTM");
        viewUTM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewUTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUTMActionPerformed(evt);
            }
        });

        viewOther.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        viewOther.setText("Other");
        viewOther.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOtherActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setText("<< Back ");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jRadioButton8.setBackground(new java.awt.Color(0, 51, 102));
        jRadioButton8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("Undergraduate");
        jRadioButton8.setToolTipText("");
        jRadioButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jRadioButton7.setBackground(new java.awt.Color(0, 51, 102));
        jRadioButton7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Postgraduate");
        jRadioButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(jLabel1)
                            .addGap(14, 14, 14))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(viewOther, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewState, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jRadioButton8)
                                    .addGap(26, 26, 26)))
                            .addComponent(viewHome, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewUTM, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton7)
                        .addGap(12, 12, 12)
                        .addComponent(jRadioButton8)
                        .addGap(18, 18, 18)
                        .addComponent(viewState, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewHome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewUTM, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewOther, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1313, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStateActionPerformed
        // TODO add your handling code here:
        if(jRadioButton8.isSelected())
        {
            //jRadioButton7.
            
            try
            {
                ArrayList <Student> stdList = new ArrayList<Student>();
                FileReader file = new FileReader("Undergraduate.txt");
                Scanner readFile = new Scanner(file);

                while(readFile.hasNext())
                {
                    String sid = readFile.next();
                    String sPass = readFile.next();
                    String name1 = readFile.next();
                    String name2 = readFile.next();
                    String numPhone = readFile.next();
                    String stats = readFile.next();
                    String prog = readFile.next();
                    String neg = readFile.next();
                    String kolej3 = readFile.next();
                    String cLoc = readFile.next();
                    String year = readFile.next();
                    String sPlace = readFile.nextLine();
                    Student list = new Student (name1,name2,sid,numPhone,sPass,
                        stats,prog,neg,kolej3,cLoc,year) {
                        @Override
                        public void display() {
                            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        }
                    };
                    
                    stdList.add(list);
                    area1.setText("                                                                                   LIST OF ALL UNDERGRADUATE UTM'S STUDENTS\n"+
                        "------------------------------------------------------------------------------------------------------------"
                        + "---------------------------------------------------------------\n"+
                        "No"+"   "+"Name"+"\t\t"+"Metric No."+"\t"+"Program"+"\t"+"Year"+"\t"+"Current Location"+"\t"+"State"+"\n");
                    for(int i =0;i<stdList.size();i++)
                    {
                        
                        area1.append((i+1)+"    "+stdList.get(i).getFullname()+"\t"
                            +stdList.get(i).getNoMatric()+"\t"+stdList.get(i).getProgram()+"\t"
                            +stdList.get(i).getYear()+"\t"+stdList.get(i).getCurrent()
                            +"\t\t"+stdList.get(i).getState()+"\n");

                    }
                    try
                    {
                        if(list.getState().equals("Terengganu"))
                        {
                            TState+=1;
                        }
                        else if(list.getState().equals("Wilayah_Persekutuan"))
                        {
                            wilayah+=1;
                        }
                        else if(list.getState().equals("Selangor"))
                        {
                            selangor+=1;
                        }
                        else if(list.getState().equals("Melaka"))
                        {

                        }
                        else if(list.getState().equals("Johor_Bahru"))
                        {
                            JB+=1;
                        }
                        else if(list.getState().equals("N.Sembilan"))
                        {
                            ns+=1;
                        }
                        else if(list.getState().equals("Kedah"))
                        {
                            kedah+=1;
                        }
                        else if(list.getState().equals("Perlis"))
                        {
                            perlis+=1;
                        }else if(list.getState().equals("Perak"))
                        {
                            perak+=1;
                        }
                        else if(list.getState().equals("Pulau_Pinang"))
                        {
                            pp+=1;
                        }
                        else if(list.getState().equals("Pahang"))
                        {
                            pahang+=1;
                        }
                        else if(list.getState().equals("Kelantan"))
                        {
                            kelantan+=1;
                        }
                        else if(list.getState().equals("Sabah"))
                        {
                            sabah+=1;
                        }
                        else if(list.getState().equals("Sarawak"))
                        {
                            sar+=1;
                        }
                    }catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null,"Auch! Data does not exits.");
                    }

                    area1.append("\n"+"Jumlah bilangan mengikut negeri"+"\n"
                        +"Wilayah "+"\t: "+wilayah+"\n"
                        +"Persekutuan "+"\n"
                        +"Selangor "+"\t: "+selangor+"\n"
                        +"Terengganu "+"\t: "+TState+"\n"
                        +"Johor Bahru "+"\t:"+JB+"\n"
                        +"Melaka "+"\t: "+melaka+"\n"
                        +"N.Sembilan "+"\t: "+ns+"\n"
                        +"Pulau Pilang "+"\t: "+pp+"\n"
                        +"Kelantan "+"\t: "+kelantan+"\n"
                        +"Perak "+"\t: "+perak+"\n"
                        +"Pahang "+"\t: "+pahang+"\n"
                        +"Perlis "+"\t: "+perlis+"\n"
                        +"Sabah "+":\t "+sabah+"\n"
                        +"sarawak "+"\t: "+sar+"\n"
                        +"Kedah "+"\t: "+kedah+"\n");

                }

            }catch (Exception e)
            {
                JOptionPane.showMessageDialog(null,"File does not exist.");
            }
        }
        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        //POSTGRADUATE
        else if(jRadioButton7.isSelected())
        {
           try
            {
                jRadioButton8.setSelected(false);
                ArrayList <Student> stdList = new ArrayList<Student>();
            FileReader file = new FileReader("Postgraduate.txt");
            Scanner readFile = new Scanner(file);
            
            while(readFile.hasNext())
            {
                String sid = readFile.next();
                String sPass = readFile.next();
                String name1 = readFile.next();
                String name2 = readFile.next();
                String numPhone = readFile.next();
                String stats = readFile.next();
                String prog = readFile.next();
                String neg = readFile.next();
                String kolej3 = readFile.next();
                String cLoc = readFile.next();
                String year = readFile.next();
                String statusStude = readFile.nextLine();
                Student list = new Student (name1,name2,sid,numPhone,sPass,
                        stats,prog,neg,kolej3,cLoc,year) {
                        @Override
                        public void display() {
                            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        }
                    };
              
                stdList.add(list);
                area1.setText("                                                                                   LIST OF ALL POSTGRADUATE UTM'S STUDENTS\n"+
                            "------------------------------------------------------------------------------------------------------------"
                        + "---------------------------------------------------------------\n"+
                            "No"+"   "+"Name"+"\t\t"+"Metric No."+"\t"+"Program"+"\t"+"Year"+"\t"+"Current Location"+"\t"+"State"+"\n");
                for(int i =0;i<stdList.size();i++)
                {
                    
                    area1.append((i+1)+"    "+stdList.get(i).getFullname()+"\t"
                            +stdList.get(i).getNoMatric()+"\t"+stdList.get(i).getProgram()+"\t"
                            +stdList.get(i).getYear()+"\t"+stdList.get(i).getCurrent()
                            +"\t\t"+stdList.get(i).getState()+"\n");
            
                }
                try
                {
                    if(list.getState().equals("Terengganu"))
                    {
                        TState+=1;
                    }
                    else if(list.getState().equals("Wilayah_Persekutuan"))
                    {
                        wilayah+=1;
                    }
                    else if(list.getState().equals("Selangor"))
                    {
                        selangor+=1;
                    }
                    else if(list.getState().equals("Melaka"))
                    {
                        
                    }
                    else if(list.getState().equals("Johor_Bahru"))
                    {
                        JB+=1;
                    }
                    else if(list.getState().equals("N.Sembilan"))
                    {
                        ns+=1;
                    }
                    else if(list.getState().equals("Kedah"))
                    {
                        kedah+=1;
                    }
                    else if(list.getState().equals("Perlis"))
                    {
                        perlis+=1;
                    }else if(list.getState().equals("Perak"))
                    {
                        perak+=1;
                    }
                    else if(list.getState().equals("Pulau_Pinang"))
                    {
                        pp+=1;
                    }
                    else if(list.getState().equals("Pahang"))
                    {
                        pahang+=1;
                    }
                    else if(list.getState().equals("Kelantan"))
                    {
                        kelantan+=1;
                    }
                    else if(list.getState().equals("Sabah"))
                    {
                        sabah+=1;
                    }
                    else if(list.getState().equals("Sarawak"))
                    {
                        sar+=1;
                    }
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"Auch! Data does not exits.");
                }
                
                 area1.append("\n"+"Jumlah bilangan mengikut negeri"+"\n"
                +"Wilayah "+"\t: "+wilayah+"\n"
                        +"Persekutuan "+"\n"
                +"Selangor "+"\t: "+selangor+"\n"
                +"Terengganu "+"\t: "+TState+"\n"
                +"Johor Bahru "+"\t:"+JB+"\n"
                +"Melaka "+"\t: "+melaka+"\n"
                +"N.Sembilan "+"\t: "+ns+"\n"
                +"Pulau Pilang "+"\t: "+pp+"\n"
                +"Kelantan "+"\t: "+kelantan+"\n"
                +"Perak "+"\t: "+perak+"\n"
                +"Pahang "+"\t: "+pahang+"\n"
                +"Perlis "+"\t: "+perlis+"\n"
                +"Sabah "+":\t "+sabah+"\n"
                +"sarawak "+"\t: "+sar+"\n"
                +"Kedah "+"\t: "+kedah+"\n");
 
            }
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"File does not exist.");
            } 
        }

    }//GEN-LAST:event_viewStateActionPerformed

    private void viewHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHomeActionPerformed
        // TODO add your handling code here:
        if(jRadioButton8.isSelected())
        {
            try
            {
                ArrayList <Student> stdList = new ArrayList<Student>();
                FileReader file = new FileReader("Undergraduate.txt");
                Scanner readFile = new Scanner(file);

                while(readFile.hasNext())
                {
                    String sid = readFile.next();
                    String sPass = readFile.next();
                    String name1 = readFile.next();
                    String name2 = readFile.next();
                    String numPhone = readFile.next();
                    String stats = readFile.next();
                    String prog = readFile.next();
                    String neg = readFile.next();
                    String kolej3 = readFile.next();
                    String cLoc = readFile.next();
                    String year = readFile.next();
                    String sPlace = readFile.nextLine();
                    Student list = new Student (name1,name2,sid,numPhone,sPass,
                        stats,prog,neg,kolej3,cLoc,year) {
                        @Override
                        public void display() {
                            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        }
                    };
                    stdList.add(list);
                    area1.setText("                                                                                   LIST OF ALL UNDERGRADUATE UTM'S STUDENTS\n"+
                        "------------------------------------------------------------------------------------------------------------"
                        + "---------------------------------------------------------------\n"+
                        "No"+"   "+"Name"+"\t\t"+"Metric No."+"\t"+"Program"+"\t"+"Year"+"\t"+"Current Location"+"\t"+"State"+"\n");
                    for(int i =0;i<stdList.size();i++)
                    {
                        int j=1;
                        if(stdList.get(i).getCurrent().equals("Home"))
                        {
                            area1.append(j+"    "+stdList.get(i).getFullname()+"\t"
                            +stdList.get(i).getNoMatric()+"\t"+stdList.get(i).getProgram()+"\t"
                            +stdList.get(i).getYear()+"\t"+stdList.get(i).getCurrent()
                            +"\t\t"+stdList.get(i).getState()+"\n");
                            j++;
                        }

                    }
                    try
                    {
                        if(list.getCurrent().equals("Home"))
                        {
                            home+=1;
                        }

                    }catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null,"Auch! Data does not exits.");
                    }
                    area1.append("\nTotal of students currently at home"+"\t: "+home);

                }

            }catch (Exception e)
            {
                JOptionPane.showMessageDialog(null,"File does not exist.");
            }
        }
        else if(jRadioButton7.isSelected())
        {
            try
            {
                ArrayList <Student> stdList = new ArrayList<Student>();
            FileReader file = new FileReader("Postgraduate.txt");
            Scanner readFile = new Scanner(file);
            
            while(readFile.hasNext())
            {
                String sid = readFile.next();
                String sPass = readFile.next();
                String name1 = readFile.next();
                String name2 = readFile.next();
                String numPhone = readFile.next();
                String stats = readFile.next();
                String prog = readFile.next();
                String neg = readFile.next();
                String kolej3 = readFile.next();
                String cLoc = readFile.next();
                String year = readFile.next();
                String statusStud = readFile.nextLine();
                 Student list = new Student (name1,name2,sid,numPhone,sPass,
                        stats,prog,neg,kolej3,cLoc,year) {
                        @Override
                        public void display() {
                            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        }
                    };
              //  Admin admin = new Admin("Lisa","A11SS3434");
               // admin.viewStud(list);
                stdList.add(list);
                area1.setText("                                                                                   LIST OF ALL POSTGRADUATE UTM'S STUDENTS\n"+
                            "------------------------------------------------------------------------------------------------------------"
                        + "---------------------------------------------------------------\n"+
                            "No"+"   "+"Name"+"\t\t"+"Metric No."+"\t"+"Program"+"\t"+"Year"+"\t"+"Current Location"+"\t"+"State"+"\n");
                for(int i =0;i<stdList.size();i++)
                {
                    int j=1;
                    if(stdList.get(i).getCurrent().equals("Home"))
                    {
                        area1.append(j+"    "+stdList.get(i).getFullname()+"\t"
                            +stdList.get(i).getNoMatric()+"\t"+stdList.get(i).getProgram()+"\t"
                            +stdList.get(i).getYear()+"\t"+stdList.get(i).getCurrent()
                            +"\t\t"+stdList.get(i).getState()+"\n");
                        j++;
                    }
                    
            
                }
                try
                {
                    if(list.getCurrent().equals("Home"))
                    {
                        home+=1;
                    }
                    
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"Auch! Data does not exits.");
                }    
                area1.append("\nTotal of students currently at home"+"\t: "+home);
       
            }
            
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"File does not exist.");
        }
       }
    }//GEN-LAST:event_viewHomeActionPerformed

    private void viewUTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUTMActionPerformed
        // TODO add your handling code here:
        int utm=0;
        if(jRadioButton8.isSelected())
        {
            try
            {
                ArrayList <Student> stdList = new ArrayList<Student>();
                FileReader file = new FileReader("Undergraduate.txt");
                Scanner readFile = new Scanner(file);

                while(readFile.hasNext())
                {
                    String sid = readFile.next();
                    String sPass = readFile.next();
                    String name1 = readFile.next();
                    String name2 = readFile.next();
                    String numPhone = readFile.next();
                    String stats = readFile.next();
                    String prog = readFile.next();
                    String neg = readFile.next();
                    String kolej3 = readFile.next();
                    String cLoc = readFile.next();
                    String year = readFile.next();
                    String sPlace = readFile.nextLine();
                    Student list = new Student (name1,name2,sid,numPhone,sPass,
                        stats,prog,neg,kolej3,cLoc,year) {
                        @Override
                        public void display() {
                            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        }
                    };
                    stdList.add(list);
                    area1.setText("                                                                                   LIST OF ALL UNDERGRADUATE UTM'S STUDENTS\n"+
                        "------------------------------------------------------------------------------------------------------------"
                        + "---------------------------------------------------------------\n"+
                        "No"+"   "+"Name"+"\t\t"+"Metric No."+"\t"+"Program"+"\t"+"Year"+"\t"+"Current Location"+"\t"+"State"+"\n");
                    for(int i =0;i<stdList.size();i++)
                    {
                        int j=1;
                        if(stdList.get(i).getCurrent().equals("UTMJB/KL"))
                        {
                            area1.append(j+"    "+stdList.get(i).getFullname()+"\t"
                            +stdList.get(i).getNoMatric()+"\t"+stdList.get(i).getProgram()+"\t"
                            +stdList.get(i).getYear()+"\t"+stdList.get(i).getCurrent()
                            +"\t\t"+stdList.get(i).getState()+"\n");

                            j++;
                        }


                    }
                    try
                    {
                        if(list.getCurrent().equals("UTMJB/KL"))
                        {
                            utm+=1;
                        }

                    }catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null,"Auch! Data does not exits.");
                    }
                    area1.append("\nTotal of students currently at UTM"+"\t: "+utm);

                }

            }catch (Exception e)
            {
                JOptionPane.showMessageDialog(null,"File does not exist.");
            }
        }
        else if(jRadioButton7.isSelected())
        {
            try
        {
             ArrayList <Student> stdList = new ArrayList<Student>();
            FileReader file = new FileReader("Postgraduate.txt");
            Scanner readFile = new Scanner(file);
            
            while(readFile.hasNext())
            {
                String sid = readFile.next();
                String sPass = readFile.next();
                String name1 = readFile.next();
                String name2 = readFile.next();
                String numPhone = readFile.next();
                String stats = readFile.next();
                String prog = readFile.next();
                String neg = readFile.next();
                String kolej3 = readFile.next();
                String cLoc = readFile.next();
                String year = readFile.next();
                String sPlace = readFile.nextLine();
                    Student list = new Student (name1,name2,sid,numPhone,sPass,
                        stats,prog,neg,kolej3,cLoc,year) {
                        @Override
                        public void display() {
                            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        }
                    };
              //  Admin admin = new Admin("Lisa","A11SS3434");
               // admin.viewStud(list);
                stdList.add(list);
                area1.setText("                                                                                   LIST OF ALL POSTGRADUATE UTM'S STUDENTS\n"+
                            "------------------------------------------------------------------------------------------------------------"
                        + "---------------------------------------------------------------\n"+
                            "No"+"   "+"Name"+"\t\t"+"Metric No."+"\t"+"Program"+"\t"+"Year"+"\t"+"Current Location"+"\t"+"State"+"\n");
                for(int i =0;i<stdList.size();i++)
                {
                    int j=1;
                    if(stdList.get(i).getCurrent().equals("UTMJB/KL"))
                    {
                        area1.append(j+"    "+stdList.get(i).getFullname()+"\t"
                            +stdList.get(i).getNoMatric()+"\t"+stdList.get(i).getProgram()+"\t"
                            +stdList.get(i).getYear()+"\t"+stdList.get(i).getCurrent()
                            +"\t\t"+stdList.get(i).getState()+"\n");
                    }
 
                }
                try
                {
                    if(list.getCurrent().equals("UTMJB/KL"))
                    {
                        utm+=1;
                    }
                    
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"Auch! Data does not exits.");
                }    
                area1.append("\nTotal of students currently at UTM"+"\t: "+utm);
       
            }
            
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"File does not exist.");
        }
        }
        
    }//GEN-LAST:event_viewUTMActionPerformed

    private void viewOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOtherActionPerformed
        // TODO add your handling code here:
        int other=0;
        if(jRadioButton8.isSelected())
        {
            try
            {
                ArrayList <Student> stdList = new ArrayList<Student>();
                FileReader file = new FileReader("Undergraduate.txt");
                Scanner readFile = new Scanner(file);

                while(readFile.hasNext())
                {
                    String sid = readFile.next();
                    String sPass = readFile.next();
                    String name1 = readFile.next();
                    String name2 = readFile.next();
                    String numPhone = readFile.next();
                    String stats = readFile.next();
                    String prog = readFile.next();
                    String neg = readFile.next();
                    String kolej3 = readFile.next();
                    String cLoc = readFile.next();
                    String year = readFile.next();
                    String sPlace = readFile.nextLine();
                    Student list = new Student (name1,name2,sid,numPhone,sPass,
                        stats,prog,neg,kolej3,cLoc,year) {
                        @Override
                        public void display() {
                            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        }
                    };
                    stdList.add(list);
                    area1.setText("                                                                                   LIST OF ALL UNDERGRADUATE UTM'S STUDENTS\n"+
                        "------------------------------------------------------------------------------------------------------------"
                        + "---------------------------------------------------------------\n"+
                        "No"+"   "+"Name"+"\t\t"+"Metric No."+"\t"+"Program"+"\t"+"Year"+"\t"+"Current Location"+"\t"+"State"+"\n");
                    for(int i =0;i<stdList.size();i++)
                    {
                        int j=1;
                        if(stdList.get(i).getCurrent().equals("Other"))
                        {
                            area1.append(j+"    "+stdList.get(i).getFullname()+"\t"
                            +stdList.get(i).getNoMatric()+"\t"+stdList.get(i).getProgram()+"\t"
                            +stdList.get(i).getYear()+"\t"+stdList.get(i).getCurrent()
                            +"\t\t"+stdList.get(i).getState()+"\n");

                            j++;
                        }

                    }
                    try
                    {
                        if(list.getCurrent().equals("Other"))
                        {
                            other+=1;
                        }

                    }catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null,"Auch! Data does not exits.");
                    }
                    area1.append("\nTotal of students currently at other"+"\t: "+other);

                }

            }catch (Exception e)
            {
                JOptionPane.showMessageDialog(null,"File does not exist.");
            }
        }
        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        ///////////POSTGRADUATE
        else if(jRadioButton7.isSelected())
        {
            try
        {
             ArrayList <Student> stdList = new ArrayList<Student>();
            FileReader file = new FileReader("Postgraduate.txt");
            Scanner readFile = new Scanner(file);
            
            while(readFile.hasNext())
            {
                String sid = readFile.next();
                String sPass = readFile.next();
                String name1 = readFile.next();
                String name2 = readFile.next();
                String numPhone = readFile.next();
                String stats = readFile.next();
                String prog = readFile.next();
                String neg = readFile.next();
                String kolej3 = readFile.next();
                String cLoc = readFile.next();
                String year = readFile.next();
                String sPlace = readFile.nextLine();
                Student list = new Student (name1,name2,sid,numPhone,sPass,
                        stats,prog,neg,kolej3,cLoc,year) {
                        @Override
                        public void display() {
                            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        }
                    };
              //  Admin admin = new Admin("Lisa","A11SS3434");
               // admin.viewStud(list);
                stdList.add(list);
                area1.setText("                                                                                   LIST OF ALL POSTGRADUATE UTM'S STUDENTS\n"+
                            "------------------------------------------------------------------------------------------------------------"
                        + "---------------------------------------------------------------\n"+
                            "No"+"   "+"Name"+"\t\t"+"Metric No."+"\t"+"Program"+"\t"+"Year"+"\t"+"Current Location"+"\t"+"State"+"\n");
                for(int i =0;i<stdList.size();i++)
                {
                    int j=1;
                    if(stdList.get(i).getCurrent().equals("Other"))
                    {
                        area1.append(j+"    "+stdList.get(i).getFullname()+"\t"
                            +stdList.get(i).getNoMatric()+"\t"+stdList.get(i).getProgram()+"\t"
                            +stdList.get(i).getYear()+"\t"+stdList.get(i).getCurrent()
                            +"\t\t"+stdList.get(i).getState()+"\n");
                    }
 
                }
                try
                {
                    if(list.getCurrent().equals("Other"))
                    {
                        other+=1;
                    }
                    
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"Auch! Data does not exits.");
                }    
                area1.append("\nTotal of students currently at other"+"\t: "+other);
       
            }
            
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"File does not exist.");
        }
        }
    }//GEN-LAST:event_viewOtherActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ViewMenu().setVisible(true);
        this.hide();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewStudentLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewStudentLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewStudentLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewStudentLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewStudentLocation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton viewHome;
    private javax.swing.JButton viewOther;
    private javax.swing.JButton viewState;
    private javax.swing.JButton viewUTM;
    // End of variables declaration//GEN-END:variables
}
